# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065853f8adc7c3d4bff051aba7f79d45b3e2d1387335a27d3115f3aa4e2dcfd21fba94381644f9c92f0fccfe0895a78dc68756f9405a4523e916a93572794c65

test:
  secret_key_base: 1d14854fe887ddc74234735728736b186afe57c1e7b74c7ec53087adc1cf1181aac0a3f40fff2c99e0bad2c89171fce6d94f4730bec3df95051381bc3df583ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
